# Generated by Django 5.0.4 on 2025-03-07 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="face_data",
        ),
    ]
